# Stage 1: Build the application
FROM python:3.9-slim AS builder

RUN apt-get update && apt-get -y install libpq-dev gcc

# Create and activate the virtual environment
RUN python -m venv /venv
ENV PATH=/venv/bin:$PATH

COPY requirements.txt /
RUN pip install --no-warn-script-location -r /requirements.txt

# Stage 2: Run the application
FROM python:3.9-slim AS final

RUN apt-get update && apt-get -y install libpq5

# Copy the virtual environment from the builder stage
COPY --from=builder /venv /venv
ENV PATH=/venv/bin:$PATH

COPY app /app
WORKDIR /app

ENTRYPOINT ["uvicorn"]
CMD ["main:app", "--host", "0.0.0.0", "--port", "5000"]