FROM python:3.9-slim

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

COPY requirements.txt /
RUN pip install -r /requirements.txt

COPY app /app
WORKDIR /app

EXPOSE 5000

ENTRYPOINT ["uvicorn"]
CMD ["main:app", "--host", "0.0.0.0", "--port", "5000"]
