apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: sunnybikes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sunnybikes
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: sunnybikes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:11-alpine
          imagePullPolicy: IfNotPresent
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sunnybikes-secret
                  key: secret1
          volumeMounts:
            - name: sunnybikes-volume
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: sunnybikes-volume
          configMap:
            name: sunnybike-configmap
            items:
              - key: init-schema.sql
                path: init-schema.sql
        - name: data
          persistentVolumeClaim:
            claimName: pvc-postgres
