apiVersion: v1
kind: Service
metadata:
  name: sunnybikes
  namespace: sunnybikes
spec:
  type: LoadBalancer
  selector:
    app: sunnybikes
    env: production
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunnybikes
  namespace: sunnybikes
spec:
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  replicas: 3
  selector:
    matchLabels:
      app: sunnybikes
      env: production
  template:
    metadata:
      labels:
        app: sunnybikes
        env: production
    spec:
      containers:
        - name: sunnybikes
          image: pugillum/sunnybikes:stable
          ports:
            - containerPort: 80
          env:
            - name: PG_PORT
              value: "5432"
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sunnybikes-secret
                  key: secret1
            - name: PG_HOST
              value: "postgres.sunnybikes.svc.cluster.local"
